### ISSUE TITLE
Home screen - My Media (small) not optimize

### ISSUE THREAD

**Issue by Oyo95** [lscambo13/ElegantFin#1]
Hi !
Thanks you for your work ! I Apreciate your custom theme !
Could you (maybe) reorganize when we use in the home screen : My Media (small) please ?

![Screenshot_20241201-203229](https://github.com/user-attachments/assets/4a6155b7-640f-41d5-b1dc-a4d282ed7a88)

Many thanks again :)

**Comment by lscambo13** [comment]
It should be fixed in the latest version (v24.12.03). 

You may need to hard refresh the page to make sure that the latest theme is pulled.

To make sure that you are using the latest version of ElegantFin, check the version number at the bottom in the Dashboard screen.

Please check and report.

c17294ac68a374c1e8f62ecb02338a4add42522b

**Comment by Oyo95** [comment]
Hi !

On my mobile inhabe the same issue :/
![Screenshot_20241207-175630](https://github.com/user-attachments/assets/63747995-3568-499a-9090-d8e491482796)

I have deleted the css link, reboot jellyfin, reset cache on my phone, added the css link and test

**Comment by lscambo13** [comment]
These small media buttons have been fixed. See below:

![image](https://github.com/user-attachments/assets/5fb13609-d9be-432c-a7b0-79ce906920d5)

If you have this issue, it is possible that you are still using an older version.  To verify, go to Settings > Dashboard > scroll to bottom > Find the ElegantFin version number in the footer under Jellyfin. It should read **ElegantFin v24.12.03**.

![image](https://github.com/user-attachments/assets/f6d94f8d-b217-4d40-8059-a9c440eee073)

**Comment by Oyo95** [comment]
My Bad you're right :) i have deleted the container & recreate and i have the new version ! Many thanks for your help !

**Comment by Oyo95** [comment]
Do you think it's possible to modify and have the overlays on this screen depending on the size of the phone and the number of users displayed on the screen, like one, two, or three users?
![Screenshot_20241207-185742](https://github.com/user-attachments/assets/bad5facf-9da3-4df9-9387-5a185b453853)

**Comment by Oyo95** [comment]
Same question about catalog extension & extension :)

**Comment by lscambo13** [comment]
These card sizes have also been fixed. 

![image](https://github.com/user-attachments/assets/57d4e806-d004-4a8b-ac78-5782685db591)

I'll release an update in coming days.

Stay tuned.

**Comment by lscambo13** [comment]
An update has been released to fix some issues. It should be available automatically. To confirm that you have the latest version, check the version number in the Dashboard footer. It should now read `ElegantFin v24.12.11`.

Be sure to check out the [release notes](https://github.com/lscambo13/ElegantFin/releases/tag/v24.12.11) and the [troubleshooting section](https://github.com/lscambo13/ElegantFin?tab=readme-ov-file#%EF%B8%8F-troubleshooting).

Let me know if you notice any problems.

**Comment by Oyo95** [comment]
Perfect many thanks !
