### ISSUE TITLE
Please add random backgrounds

### ISSUE THREAD

**Issue by bebeidon** [lscambo13/ElegantFin#10]
random background like the vanilla theme. this can be toggled on and off already in the menu, right now the switch does nothing with this theme.

**Comment by lscambo13** [comment]
That has been fixed, but not released yet. Wait for a few days. I'll release it with some more bug fixes.

**Comment by lscambo13** [comment]
An update has been released to fix some issues. It should be available automatically. To confirm that you have the latest version, check the version number in the Dashboard footer. It should now read `ElegantFin v24.12.11`.

Be sure to check out the [release notes](https://github.com/lscambo13/ElegantFin/releases/tag/v24.12.11) and the [troubleshooting section](https://github.com/lscambo13/ElegantFin?tab=readme-ov-file#%EF%B8%8F-troubleshooting).

Let me know if you notice any problems.

**Comment by lscambo13** [comment]
Closing this issue as completed in f1d2f14a307967ab20c299193746a6b5eaefa136.
