### ISSUE TITLE
TV Mode

### ISSUE THREAD

**Issue by DumberSoft** [lscambo13/ElegantFin#11]
![image](https://github.com/user-attachments/assets/f29c9674-83c1-463b-b344-a24fe20c357b)
I see it in TV mode and it is poorly designed, when would they be designing it, the rest looks excellent, good work.

**Comment by lscambo13** [comment]
Does it happen on the official theme as well?

Please share the following information:
TV model and platform 
TV resolution
TV app version
A screenshot with the default theme

**Comment by lscambo13** [comment]
This issue has been fixed in the latest update, [v24.12.20](https://github.com/lscambo13/ElegantFin/releases/tag/v24.12.20). 

I am closing this issue for now, but if you still face problems, feel free to reopen it.
