### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Wernouxe** [lscambo13/ElegantFin#16]
**Is your feature request related to a problem? Please describe.**
The progress bars of Jellyfin have no style

**Describe the solution you'd like**
Add a style to the progress bars

**Additional context**
There's a progress bar on Jellyseerr that you might like to adopt 🤔

![progess_bar_jellyseerr](https://github.com/user-attachments/assets/4f36dec0-c46d-444c-b115-69a069d35e90)
![progess_bar_jellyfin_1](https://github.com/user-attachments/assets/3ed0a4ba-8138-4625-91dc-b9aa213f3cbb)
![progess_bar_jellyfin_2](https://github.com/user-attachments/assets/c1f614a3-06c0-4b54-ad13-9f7baed3b6f8)

**Comment by Tormak9970** [comment]
@lscambo13 Does this look good for the progress bar styling?
![image](https://github.com/user-attachments/assets/ecbc5da2-cc23-483c-af3b-d6e41cbce8b8)

**Comment by lscambo13** [comment]
> @lscambo13 Does this look good for the progress bar styling? ![image](https://private-user-images.githubusercontent.com/63308171/398825300-ecbc5da2-cc23-483c-af3b-d6e41cbce8b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMDQ2NDgsIm5iZiI6MTczNTMwNDM0OCwicGF0aCI6Ii82MzMwODE3MS8zOTg4MjUzMDAtZWNiYzVkYTItY2MyMy00ODNjLWFmM2ItZDZlNDFjYmNlOGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDEyNTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZmRjNmQzOTY2OWU3ZmJmYmE2N2M2MzllY2ViNDBkMWIzYjNjNzJkNGM4MTIyY2FhNDE5ODFkMjM1OGI0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vv8zuokUE0S5edcdDGGzATc9at6G44nC6CRvg1I3sss)

Looks great!
