### ISSUE TITLE
[Bug] misaligned buttons in details page

### ISSUE THREAD

**Issue by coxde** [lscambo13/ElegantFin#2]
Nice theme!

For both movies and shows, buttons are misaligned in details page. Tested on jellyfin media player 1.11.1

![image](https://github.com/user-attachments/assets/d73a5490-2ebe-42f4-b5c1-8a56e72342e8)

**Comment by lscambo13** [comment]
Jellyfin Media Player has this bug as it may be using an outdated web engine internally.

Web version and the android app are fine. 

I will need more time to test and fix the issues with JMP.

**Comment by lscambo13** [comment]
@coxde can you confirm if it has been fixed for you?

![image](https://github.com/user-attachments/assets/4e7ebaca-2c9b-432d-b460-aca0c57c4417)

**Comment by coxde** [comment]
> @coxde can you confirm if it has been fixed for you?
> 
> ![image](https://private-user-images.githubusercontent.com/32175188/399181524-4e7ebaca-2c9b-432d-b460-aca0c57c4417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MDA0MDYsIm5iZiI6MTczNTUwMDEwNiwicGF0aCI6Ii8zMjE3NTE4OC8zOTkxODE1MjQtNGU3ZWJhY2EtMmM5Yi00MzJkLWI0NjAtYWNhMGM1N2M0NDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDE5MjE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZDI4NTkyMWE4YjEwOTVmMDllYTEyNTg5OTM1ODVjM2E4NzhkNTM0Yzk3YmQ4NDc4MDVhOGUxNWY2OTgyMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K67qhf0Cu05T0-MRyiBl3qk-r5tFMX8KFS78mDUEcu4)

Yeah it works pretty well for me, thanks!

**Comment by lscambo13** [comment]
Awesome! Thanks for confirming.
