### ISSUE TITLE
Use logo

### ISSUE THREAD

**Issue by Wernouxe** [lscambo13/ElegantFin#22]
**Is your feature request related to a problem? Please describe.**
It’s not a major issue, but using textual titles instead of logos makes the interface less intuitive and visually appealing.

**Describe the solution you'd like**
Replace textual titles with logos.

**Additional context**
<img src="https://github.com/user-attachments/assets/4cb3a90f-2c29-4953-a22c-841de5b592f4"  width="200" />
<img src="https://github.com/user-attachments/assets/5e615427-4351-4584-9bd3-75f02458d90e"  width="200" />

**Comment by lscambo13** [comment]
Unfortunately, these clear logos are too unpredictable to be integrated into the theme cohesively and consistently. Their color dimensions and availability vary wildly among different movies/tv shows, so they cannot be a good replacement for written titles.
