### ISSUE TITLE
Overlap options

### ISSUE THREAD

**Issue by donchi40** [lscambo13/ElegantFin#4]
First time posting so bear with me if the picture doesn't show...
Thank you for this theme... I like it a lot and it fixed an issue with the stock theme I was using.

One issue I've found is I clicked on one of the live TV shows (main page, under Live TV, On Now, and I get to the page and see this overlap between the "Record series" and "Record" buttons:

![overlap](https://github.com/user-attachments/assets/6c940b4a-3514-4a11-8202-3b17cf26b72d)

**Comment by donchi40** [comment]
Follow up... This problem appears to be in Jellyfin Media player only... I just opened the server web page directly and don't see this issue. 
Which also brings up another issue but I'll open another case.

**Comment by lscambo13** [comment]
Jellyfin Media Player has this bug as it may be using an outdated web engine internally, but web version and the android app are fine. 

I will need more time to test and fix the issues with JMP.

**Comment by lscambo13** [comment]
@donchi40 can you show me how it looks for you with the latest version?

**Comment by donchi40** [comment]
Looks perfect now. Thank you so much.
<img width="469" alt="image" src="https://github.com/user-attachments/assets/eaf06825-fe3a-406c-b922-bd97562e4973" />
