### ISSUE TITLE
Display differences between Jellyfin server versus Jellyfin Media Player

### ISSUE THREAD

**Issue by donchi40** [lscambo13/ElegantFin#5]
So if I log into the server web page, the main page appears to be perfect... Good text size, image sizes, and good separation spaces between them.
However, when I open the Jellyfin Media Player page, the images are larger and there is no space between the images. See screen shot below of both. 
I believe another user reported a similar issue, but I just wanted to point out the server page shows it perfectly. So only the JMP is having the issue.
Jellyfin server 10.10.2 and JMP 1.11.1
![screen1](https://github.com/user-attachments/assets/844f5b3a-4ef8-4171-aaf3-f8ed64128b43)
![screen2](https://github.com/user-attachments/assets/b967bb42-4293-48e0-878b-a336b61be124)

**Comment by lscambo13** [comment]
Jellyfin Media Player has this bug as it may be using an old web engine internally, but web version and the android app are fine. 

I will need more time to test and fix the issues with JMP.

**Comment by lscambo13** [comment]
This is been confirmed as fixed.

https://github.com/lscambo13/ElegantFin/issues/3

**Comment by donchi40** [comment]
I understand you closing the issue but just wanted to give an update.
I reloaded the page but no go. Then I read what you told the other guy and logged out but still no go.
Then I followed the steps to delete the cache folder and now it's working. 
Thanks...
