### ISSUE TITLE
syncplay button unavailable in theme

### ISSUE THREAD

**Issue by poulpor** [lscambo13/ElegantFin#9]
Hi, I really like your EleganFin theme but can't use it because of the lack of "Syncplay" button, usually next to the "cast" icon in the upper right corner.
I suppose it's not a Jellyfin feature you're using but if you could add it in a future release, it would be great!
![Capture d’écran 2024-12-04 à 16 50 48](https://github.com/user-attachments/assets/1d4def86-258a-4e5b-87f9-213e59340341)

**Comment by lscambo13** [comment]
I might re-enable it, but in the meantime, if you are willing to modify and selfhost the theme, I can show you how to get that button back.

Simply find and remove `.headerSyncButton,` from the theme css file.

**Comment by poulpor** [comment]
Thank you very much for your quick reply and workaround, I removed .headerSyncButton and just copy/pasted the whole code in Jellyfin's CSS field!

**Comment by lscambo13** [comment]
Awesome! Sync button has been fixed in 2dc26ab929b18e365208543d8db8dab6f2f1c295, so do look out for a future update.

**Comment by lscambo13** [comment]
An update has been released to fix some issues. It should be available automatically. To confirm that you have the latest version, check the version number in the Dashboard footer. It should now read `ElegantFin v24.12.11`.

Be sure to check out the [release notes](https://github.com/lscambo13/ElegantFin/releases/tag/v24.12.11) and the [troubleshooting section](https://github.com/lscambo13/ElegantFin?tab=readme-ov-file#%EF%B8%8F-troubleshooting).

Let me know if you notice any problems.

**Comment by lscambo13** [comment]
Closing this issue as completed in 2dc26ab929b18e365208543d8db8dab6f2f1c295.
